/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas.cliente;

import controladores.CarritoController;
import java.awt.BorderLayout;
import java.awt.Image;
import java.lang.System.Logger.Level;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import modelos.Ropa;
import modelos.Usuario;
import utiles.SesionUtil;

/**
 *
 * @author josha
 */
public class ClientePanelProducto extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClientePanelProducto.class.getName());

    /**
     * Creates new form ClientePanelProducto
     */
    public ClientePanelProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void mostrarProducto(Ropa ropa) {
        ropaActual = ropa;
        nombreProducto.setText(ropa.getNombre());
        modeloProducto.setText("Modelo: " + ropa.getModelo());
        precioProducto.setText("Precio: $" + ropa.getPrecio());
        colorProducto.setText("Color: " + ropa.getColor());
        tallaProducto.setText("Talla: " + ropa.getTalla());
        descripcionProducto.setText("<html><body style='width: 200px'>" + ropa.getDescripcion() + "</body></html>");

        // Cargar imagen si existe
        try {
            if (ropa.getFoto() != null && !ropa.getFoto().isEmpty()) {
                ImageIcon icon = new ImageIcon("imagenes/ropa/" + ropa.getFoto());
                Image img = icon.getImage().getScaledInstance(imagenProductoPanel.getWidth(), imagenProductoPanel.getHeight(), Image.SCALE_SMOOTH);
                imagenProductoPanel.setLayout(new BorderLayout());
                JLabel imagenLabel = new JLabel(new ImageIcon(img));
                imagenProductoPanel.removeAll();
                imagenProductoPanel.add(imagenLabel, BorderLayout.CENTER);
                imagenProductoPanel.revalidate();
                imagenProductoPanel.repaint();
            }
        } catch (Exception e) {
            //logger.log(Level.WARNING, "Error al cargar imagen", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeloProducto = new javax.swing.JLabel();
        precioProducto = new javax.swing.JLabel();
        colorProducto = new javax.swing.JLabel();
        tallaProducto = new javax.swing.JLabel();
        descripcionProducto = new javax.swing.JLabel();
        regresarButton = new javax.swing.JButton();
        agregarAlCarrito = new javax.swing.JButton();
        imagenProductoPanel = new javax.swing.JPanel();
        nombreProductoPanel = new javax.swing.JPanel();
        nombreProducto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        modeloProducto.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        modeloProducto.setText("Talla:");

        precioProducto.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        precioProducto.setText("Descuento:");

        colorProducto.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        colorProducto.setText("Precio:");

        tallaProducto.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        tallaProducto.setText("Disponibilidad:");

        descripcionProducto.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        descripcionProducto.setText("Descripcion del producto:");

        regresarButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });

        agregarAlCarrito.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        agregarAlCarrito.setText("Agregar a carrito");
        agregarAlCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAlCarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagenProductoPanelLayout = new javax.swing.GroupLayout(imagenProductoPanel);
        imagenProductoPanel.setLayout(imagenProductoPanelLayout);
        imagenProductoPanelLayout.setHorizontalGroup(
            imagenProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        imagenProductoPanelLayout.setVerticalGroup(
            imagenProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        nombreProductoPanel.setBackground(new java.awt.Color(255, 204, 204));

        nombreProducto.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        nombreProducto.setForeground(new java.awt.Color(153, 153, 153));
        nombreProducto.setText("Nombre del producto");

        javax.swing.GroupLayout nombreProductoPanelLayout = new javax.swing.GroupLayout(nombreProductoPanel);
        nombreProductoPanel.setLayout(nombreProductoPanelLayout);
        nombreProductoPanelLayout.setHorizontalGroup(
            nombreProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nombreProductoPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nombreProductoPanelLayout.setVerticalGroup(
            nombreProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nombreProductoPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(nombreProducto)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenProductoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tallaProducto))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agregarAlCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modeloProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(regresarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
            .addComponent(nombreProductoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nombreProductoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(descripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(colorProducto)
                        .addGap(18, 18, 18)
                        .addComponent(precioProducto)
                        .addGap(18, 18, 18)
                        .addComponent(tallaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modeloProducto)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarAlCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regresarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imagenProductoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        this.dispose();
        ClientePanelProductos nuevoPProductos = new ClientePanelProductos(null, true);
        nuevoPProductos.setVisible(true);
    }//GEN-LAST:event_regresarButtonActionPerformed

    private void agregarAlCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAlCarritoActionPerformed
        if (ropaActual == null) {
            return;
        }

        Usuario usuarioActual = SesionUtil.getUsuarioActual();
        if (usuarioActual == null) {
            JOptionPane.showMessageDialog(this, "Debe iniciar sesión para agregar al carrito.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        CarritoController carritoController = new CarritoController();

        try {
            carritoController.agregarAlCarrito(usuarioActual.getNombre(), ropaActual, 1);
            JOptionPane.showMessageDialog(this, "Producto agregado al carrito.");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al agregar el producto al carrito.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_agregarAlCarritoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ClientePanelProducto dialog = new ClientePanelProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private Ropa ropaActual;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAlCarrito;
    private javax.swing.JLabel colorProducto;
    private javax.swing.JLabel descripcionProducto;
    private javax.swing.JPanel imagenProductoPanel;
    private javax.swing.JLabel modeloProducto;
    private javax.swing.JLabel nombreProducto;
    private javax.swing.JPanel nombreProductoPanel;
    private javax.swing.JLabel precioProducto;
    private javax.swing.JButton regresarButton;
    private javax.swing.JLabel tallaProducto;
    // End of variables declaration//GEN-END:variables
}
