/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas.admin;

import vistas.admin.AdminPanelCategorias;
import vistas.admin.AdminPanelAgregarProducto;
import com.formdev.flatlaf.FlatDarculaLaf;
import vistas.Login;
import vistas.Registro;

/**
 *
 * @author Villegas Velazquez Alejandro
 */
public class AdminPanelHome extends javax.swing.JDialog {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanelHome(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloBanerPanel = new javax.swing.JPanel();
        tituloPanelLabel = new javax.swing.JLabel();
        agregarCategoriaButton = new javax.swing.JButton();
        agregarUsuarioAdminButton = new javax.swing.JButton();
        cerrarSesionButton = new javax.swing.JButton();
        historialButton = new javax.swing.JButton();
        agregarProductoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloBanerPanel.setBackground(new java.awt.Color(102, 51, 255));

        tituloPanelLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tituloPanelLabel.setText("Panel Administrador");

        javax.swing.GroupLayout tituloBanerPanelLayout = new javax.swing.GroupLayout(tituloBanerPanel);
        tituloBanerPanel.setLayout(tituloBanerPanelLayout);
        tituloBanerPanelLayout.setHorizontalGroup(
            tituloBanerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloBanerPanelLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(tituloPanelLabel)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        tituloBanerPanelLayout.setVerticalGroup(
            tituloBanerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloBanerPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(tituloPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        agregarCategoriaButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        agregarCategoriaButton.setText("Agregar Categoria");
        agregarCategoriaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarCategoriaButtonMouseClicked(evt);
            }
        });
        agregarCategoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCategoriaButtonActionPerformed(evt);
            }
        });

        agregarUsuarioAdminButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        agregarUsuarioAdminButton.setText("Agregar usuario Admin");
        agregarUsuarioAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarUsuarioAdminButtonActionPerformed(evt);
            }
        });

        cerrarSesionButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        cerrarSesionButton.setText("Cerrar Sesión");
        cerrarSesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionButtonActionPerformed(evt);
            }
        });

        historialButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        historialButton.setText("Ver Historial ");
        historialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialButtonActionPerformed(evt);
            }
        });

        agregarProductoButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        agregarProductoButton.setText("Agregar Producto");
        agregarProductoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarProductoButtonMouseClicked(evt);
            }
        });
        agregarProductoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloBanerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agregarProductoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarUsuarioAdminButton)
                .addGap(18, 18, 18)
                .addComponent(agregarCategoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cerrarSesionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(historialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloBanerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarUsuarioAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarCategoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarProductoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(cerrarSesionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarUsuarioAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarUsuarioAdminButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Registro nuevoRegistro = new Registro(null, true);
        nuevoRegistro.setVisible(true);
    }//GEN-LAST:event_agregarUsuarioAdminButtonActionPerformed

    private void agregarCategoriaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarCategoriaButtonMouseClicked
        this.dispose();
        AdminPanelCategorias panelCategorias = new AdminPanelCategorias(null, true);
        panelCategorias.setVisible(true);
    }//GEN-LAST:event_agregarCategoriaButtonMouseClicked

    private void cerrarSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionButtonActionPerformed
        this.dispose();
        Login nuevoLogin = new Login(null, true);
        nuevoLogin.setVisible(true);
    }//GEN-LAST:event_cerrarSesionButtonActionPerformed

    private void historialButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
        AdminPanelHistorial panelHistorial = new AdminPanelHistorial(null, true);
        panelHistorial.setVisible(true);
    }

    private void agregarProductoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarProductoButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarProductoButtonMouseClicked

    private void agregarProductoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoButtonActionPerformed
        this.dispose();
        AdminPanelProductos nuevoAdminPanelProductos = new AdminPanelProductos(null, true);
        nuevoAdminPanelProductos.setVisible(true);
    }//GEN-LAST:event_agregarProductoButtonActionPerformed

    private void agregarCategoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCategoriaButtonActionPerformed
        this.dispose();
        AdminPanelCategorias nuevoAdminPanelCategorias = new AdminPanelCategorias(null, true);
        nuevoAdminPanelCategorias.setVisible(true);
    }//GEN-LAST:event_agregarCategoriaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* --- CÓDIGO PARA INICIAR FLATLAF --- */
    try {
        // Usamos el tema Darcula que ya habías seleccionado
        FlatDarculaLaf.setup();
    } catch (Exception ex) {
        System.err.println("No se pudo inicializar el Look and Feel FlatLaf.");
    }
    /* --- FIN DEL CÓDIGO DE FLATLAF --- */


    /* Creamos y mostramos la ventana UNA SOLA VEZ */
    java.awt.EventQueue.invokeLater(new Runnable() {
        @Override
public void run() {
            AdminPanelHome dialog = new AdminPanelHome(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCategoriaButton;
    private javax.swing.JButton agregarProductoButton;
    private javax.swing.JButton agregarUsuarioAdminButton;
    private javax.swing.JButton cerrarSesionButton;
    private javax.swing.JButton historialButton;
    private javax.swing.JPanel tituloBanerPanel;
    private javax.swing.JLabel tituloPanelLabel;
    // End of variables declaration//GEN-END:variables
}
