/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas.admin;

import controladores.CategoriaController;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelos.Categoria;
import com.formdev.flatlaf.FlatDarculaLaf;

/**
 *
 * @author Villegas Velazquez Alejandro
 */
public class AdminPanelCategorias extends javax.swing.JDialog {

    /**
     * Creates new form AdminPanelCategorias
     */
    public AdminPanelCategorias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloBanerPanel = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        BotonEliminarCategoria = new javax.swing.JButton();
        nombreCategoriaLabel = new javax.swing.JLabel();
        nombreCategoriaTextField = new javax.swing.JTextField();
        descripcionCategoriaLabel = new javax.swing.JLabel();
        descripcionCategoriaTextField = new javax.swing.JTextField();
        guardarButton = new javax.swing.JButton();
        seleccioneImagenLabel = new javax.swing.JLabel();
        imagenCategoriaFileChooser = new javax.swing.JFileChooser();
        vistaPrevia = new javax.swing.JLabel();
        regresarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloBanerPanel.setBackground(new java.awt.Color(51, 0, 102));

        tituloLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        tituloLabel.setText("CREACÍON DE CATEGORÍA");

        BotonEliminarCategoria.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        BotonEliminarCategoria.setText("Eliminacion de Categoria");
        BotonEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tituloBanerPanelLayout = new javax.swing.GroupLayout(tituloBanerPanel);
        tituloBanerPanel.setLayout(tituloBanerPanelLayout);
        tituloBanerPanelLayout.setHorizontalGroup(
            tituloBanerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloBanerPanelLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(BotonEliminarCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(104, 104, 104))
        );
        tituloBanerPanelLayout.setVerticalGroup(
            tituloBanerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloBanerPanelLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(tituloBanerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloBanerPanelLayout.createSequentialGroup()
                        .addComponent(BotonEliminarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloBanerPanelLayout.createSequentialGroup()
                        .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        nombreCategoriaLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        nombreCategoriaLabel.setText("Nombre de categoría ");

        nombreCategoriaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCategoriaTextFieldActionPerformed(evt);
            }
        });

        descripcionCategoriaLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        descripcionCategoriaLabel.setText("Descripcion de categoría");

        descripcionCategoriaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionCategoriaTextFieldActionPerformed(evt);
            }
        });

        guardarButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        guardarButton.setText("Guardar Categoría");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        seleccioneImagenLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        seleccioneImagenLabel.setText("Seleccione imagen para la categoría");

        imagenCategoriaFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenCategoriaFileChooserActionPerformed(evt);
            }
        });

        regresarButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloBanerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1255, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descripcionCategoriaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreCategoriaLabel)
                    .addComponent(descripcionCategoriaTextField)
                    .addComponent(nombreCategoriaTextField))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(imagenCategoriaFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(104, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(seleccioneImagenLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarButton)
                .addGap(397, 397, 397)
                .addComponent(regresarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloBanerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccioneImagenLabel)
                    .addComponent(nombreCategoriaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(vistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 263, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreCategoriaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(descripcionCategoriaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descripcionCategoriaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(imagenCategoriaFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regresarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 36, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descripcionCategoriaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionCategoriaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionCategoriaTextFieldActionPerformed

    private void nombreCategoriaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCategoriaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCategoriaTextFieldActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
 String nombre = nombreCategoriaTextField.getText().trim();
    String descripcion = descripcionCategoriaTextField.getText().trim();

    if (nombre.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El nombre de la categoría no puede estar vacío.");
        return;
    }

    // Verifica si se seleccionó una imagen
    if (imagenSeleccionada == null || imagenSeleccionada.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar una imagen para la categoría.");
        return;
    }

    String nombreImagen = new File(imagenSeleccionada).getName();

    Categoria nuevaCategoria = new Categoria(0, nombre, descripcion, nombreImagen);
    CategoriaController controller = new CategoriaController();
    controller.agregarCategoria(nuevaCategoria);

    javax.swing.JOptionPane.showMessageDialog(this, "Categoría guardada exitosamente.");

    nombreCategoriaTextField.setText("");
    descripcionCategoriaTextField.setText("");
    vistaPrevia.setIcon(null);
    imagenSeleccionada = null;
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void imagenCategoriaFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenCategoriaFileChooserActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals(javax.swing.JFileChooser.APPROVE_SELECTION)) {
        File archivoSeleccionado = imagenCategoriaFileChooser.getSelectedFile();
        if (archivoSeleccionado != null && archivoSeleccionado.exists()) {
            try {
                File carpetaDestino = new File("imagenes/categoria");
                if (!carpetaDestino.exists()) {
                    carpetaDestino.mkdirs(); 
                }

                // Copiar archivo a la carpeta destino
                File destino = new File(carpetaDestino, archivoSeleccionado.getName());
                Files.copy(archivoSeleccionado.toPath(), destino.toPath(), StandardCopyOption.REPLACE_EXISTING);

                // Guardar ruta relativa o absoluta de la imagen
                imagenSeleccionada = destino.getPath();

                // Mostrar la imagen en el JLabel vistaPrevia
                ImageIcon icono = new ImageIcon(imagenSeleccionada);
                Image imagenEscalada = icono.getImage().getScaledInstance(vistaPrevia.getWidth(), vistaPrevia.getHeight(), Image.SCALE_SMOOTH);
                vistaPrevia.setIcon(new ImageIcon(imagenEscalada));

            } catch (java.io.IOException ex) {
                System.getLogger(AdminPanelCategorias.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    } else if (evt.getActionCommand().equals(javax.swing.JFileChooser.CANCEL_SELECTION)) {
        System.out.println("Selección cancelada");
    }
    }//GEN-LAST:event_imagenCategoriaFileChooserActionPerformed

    private void BotonEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarCategoriaActionPerformed
        AdminEliminarCategoria dialog = new AdminEliminarCategoria(null, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_BotonEliminarCategoriaActionPerformed

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        this.dispose();
        AdminPanel nuevoAPanel = new AdminPanel(null, true);
        nuevoAPanel.setVisible(true);
    }//GEN-LAST:event_regresarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* --- CÓDIGO PARA INICIAR FLATLAF --- */
    try {
        FlatDarculaLaf.setup();
    } catch (Exception ex) {
        System.err.println("No se pudo inicializar el Look and Feel FlatLaf.");
    }
    /* --- FIN DEL CÓDIGO DE FLATLAF --- */


    /* Creamos y mostramos la ventana UNA SOLA VEZ */
    java.awt.EventQueue.invokeLater(new Runnable() {
        @Override
        public void run() {
            AdminPanelCategorias dialog = new AdminPanelCategorias(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}
    
    private String imagenSeleccionada = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEliminarCategoria;
    private javax.swing.JLabel descripcionCategoriaLabel;
    private javax.swing.JTextField descripcionCategoriaTextField;
    private javax.swing.JButton guardarButton;
    private javax.swing.JFileChooser imagenCategoriaFileChooser;
    private javax.swing.JLabel nombreCategoriaLabel;
    private javax.swing.JTextField nombreCategoriaTextField;
    private javax.swing.JButton regresarButton;
    private javax.swing.JLabel seleccioneImagenLabel;
    private javax.swing.JPanel tituloBanerPanel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JLabel vistaPrevia;
    // End of variables declaration//GEN-END:variables
}
